<a href="https://colab.research.google.com/github/Sumithra-08/cprogram/blob/main/braintumor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder,StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression,LogisticRegression
from sklearn.metrics import mean_squared_error, r2_score, accuracy_score

In [2]:
df= pd.read_csv('/content/bt_dataset_t3.csv')

In [14]:
df.head(10)

,Image,Mean,Variance,Standard Deviation,Entropy,Skewness,Kurtosis,Contrast,Energy,ASM,Homogeneity,Dissimilarity,Correlation,Coarseness,PSNR,SSIM,MSE,DC,Target
0,Image1,23.448517,2538.985627,50.388348,0.651174,1.984202,5.421042,181.467713,0.781557,0.610831,0.847033,2.765411,0.968576,7.458341e-155,97.974630,0.777011,0.171163,0.303989,1
1,Image2,4.398331,834.853030,28.893823,0.953532,6.495203,43.349355,76.745886,0.972770,0.946281,0.980762,0.548605,0.959751,7.458341e-155,110.346597,0.977953,0.009913,0.839019,1
2,Image3,3.244263,642.059166,25.338886,0.966065,7.772860,61.756034,81.752406,0.980161,0.960715,0.985066,0.540411,0.944259,7.458341e-155,112.266298,0.985362,0.006372,0.849775,1
3,Image4,8.511353,1126.214187,33.559115,0.868765,3.763142,15.107579,362.291213,0.921786,0.849690,0.949295,2.765725,0.859027,7.458341e-155,101.955792,0.881015,0.068437,0.000000,0
4,Image5,21.000793,2235.316978,47.279139,0.684724,1.936029,4.722343,312.439226,0.804184,0.646711,0.880301,3.006660,0.938572,7.458341e-155,97.639870,0.766308,0.184878,0.000000,0
5,Image6,0.000000,0.000000,0.000000,1.000000,NaN,NaN,0.000000,1.000000,1.000000,1.000000,0.000000,1.000000,7.458341e-155,inf,NaN,0.000000,NaN,0
6,Image7,11.350555,998.972243,31.606522,0.761106,2.533920,7.394586,303.947978,0.854277,0.729789,0.902355,3.440551,0.866480,7.458341e-155,99.206579,0.794881,0.128889,0.000000,0
7,Image8,0.405136,68.378718,8.269143,0.994724,20.388025,416.843433,17.789156,0.996932,0.993873,0.997885,0.114400,0.886144,7.458341e-155,111.371193,0.985175,0.007830,0.410458,1
8,Image9,5.955872,937.438650,30.617620,0.926931,5.015434,26.150440,57.226813,0.956961,0.915774,0.974157,0.507706,0.973263,7.458341e-155,111.439129,0.981891,0.007708,0.914484,1
9,Image10,6.184021,895.196827,29.919840,0.917259,4.707172,23.168174,73.714121,0.951172,0.904729,0.969454,0.686158,0.963931,7.458341e-155,113.069960,0.983963,0.005295,0.945252,1

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1644 entries, 0 to 1643
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Image               1644 non-null   object
 1   Mean                1644 non-null   float64
 2   Variance            1644 non-null   float64
 3   Standard Deviation  1644 non-null   float64
 4   Entropy             1644 non-null   float64
 5   Skewness            1275 non-null   float64
 6   Kurtosis            1275 non-null   float64
 7   Contrast            1644 non-null   float64
 8   Energy              1644 non-null   float64
 9   ASM                 1644 non-null   float64
 10  Homogeneity         1644 non-null   float64
 11  Dissimilarity       1644 non-null   float64
 12  Correlation         1644 non-null   float64
 13  Coarseness          1644 non-null   float64
 14  PSNR                1644 non-null   float64
 15  SSIM                1275 non-null   float64
 16  MSE                 1644 non-null   float64
 17  DC                  1546 non-null   float64
 18  Target              1644 non-null   int64
dtypes: float64(17), int64(1), object(1)
memory usage: 244.2+ KB

In [16]:
df.isnull().sum()

Image                   0
Mean                    0
Variance                0
Standard Deviation      0
Entropy                 0
Skewness              369
Kurtosis              369
Contrast                0
Energy                  0
ASM                     0
Homogeneity             0
Dissimilarity           0
Correlation             0
Coarseness              0
PSNR                    0
SSIM                  369
MSE                     0
DC                     98
Target                  0
dtype: int64

In [17]:
df['Skewness'].fillna(df['Skewness'].mean(),inplace=True)
df['Kurtosis'].fillna(df['Kurtosis'].mean(),inplace=True)
df['SSIM'].fillna(df['SSIM'].mean(),inplace=True)
df['DC'].fillna(df['DC'].mean(),inplace=True)

/tmp/ipykernel_1079/3209605079.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Skewness'].fillna(df['Skewness'].mean(),inplace=True)
/tmp/ipykernel_1079/3209605079.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Kurtosis'].fillna(df['Kurtosis'].mean(),inplace=True)
/tmp/ipykernel_1079/3209605079.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['SSIM'].fillna(df['SSIM'].mean(),inplace=True)
/tmp/ipykernel_1079/3209605079.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['DC'].fillna(df['DC'].mean(),inplace=True)

In [18]:
df.isnull().sum()

Image                 0
Mean                  0
Variance              0
Standard Deviation    0
Entropy               0
Skewness              0
Kurtosis              0
Contrast              0
Energy                0
ASM                   0
Homogeneity           0
Dissimilarity         0
Correlation           0
Coarseness            0
PSNR                  0
SSIM                  0
MSE                   0
DC                    0
Target                0
dtype: int64

In [19]:
df=df.drop(columns=['Image'],axis=1)
X=df.drop(columns=['Target'],axis=1)
Y=df['Target']

In [20]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,stratify=Y,random_state=42)

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1644 entries, 0 to 1643
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Mean                1644 non-null   float64
 1   Variance            1644 non-null   float64
 2   Standard Deviation  1644 non-null   float64
 3   Entropy             1644 non-null   float64
 4   Skewness            1644 non-null   float64
 5   Kurtosis            1644 non-null   float64
 6   Contrast            1644 non-null   float64
 7   Energy              1644 non-null   float64
 8   ASM                 1644 non-null   float64
 9   Homogeneity         1644 non-null   float64
 10  Dissimilarity       1644 non-null   float64
 11  Correlation         1644 non-null   float64
 12  Coarseness          1644 non-null   float64
 13  PSNR                1644 non-null   float64
 14  SSIM                1644 non-null   float64
 15  MSE                 1644 non-null   float64
 16  DC                  1644 non-null   float64
 17  Target              1644 non-null   int64
dtypes: float64(17), int64(1)
memory usage: 231.3 KB

In [22]:
model= LogisticRegression()

In [23]:
X_train=X_train.replace([np.inf,-np.inf],np.nan)
X_test=X_test.replace([np.inf,-np.inf],np.nan)

In [24]:
X_train.isnull().sum()

Mean                   0
Variance               0
Standard Deviation     0
Entropy                0
Skewness               0
Kurtosis               0
Contrast               0
Energy                 0
ASM                    0
Homogeneity            0
Dissimilarity          0
Correlation            0
Coarseness             0
PSNR                  77
SSIM                   0
MSE                    0
DC                     0
dtype: int64

In [25]:
X_train.fillna(X_train.mean(),inplace=True)
X_test.fillna(X_test.mean(),inplace=True)

In [26]:
S= StandardScaler()

In [27]:
X_value=S.fit_transform(X_train)

In [28]:
S.fit(X_train,Y_train)

StandardScaler()

In [29]:
model.fit(X_train,Y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [57]:
X_train_predict=model.predict(X_train)
X_train_accuracy=accuracy_score(X_train_predict,Y_train)
print("Accuracy score X_train:",X_train_accuracy)

Accuracy score X_train: 0.8790874524714829

In [58]:
X_test_predict=model.predict(X_test)
X_test_accuracy=accuracy_score(X_test_predict,Y_test)
print("Accuracy score X_traiX_test:",X_test_accuracy)

Accuracy score X_traiX_test: 0.8693009118541033

In [67]:
np.isinf(X).sum()

Mean                   0
Variance               0
Standard Deviation     0
Entropy                0
Skewness               0
Kurtosis               0
Contrast               0
Energy                 0
ASM                    0
Homogeneity            0
Dissimilarity          0
Correlation            0
Coarseness             0
PSNR                  98
SSIM                   0
MSE                    0
DC                     0
dtype: int64

In [5]:
new_data=(23.448517,2538.985627,50.388348,0.65117,1.984202,5.421042,181.467713,0.781557,0.610831,0.847033,2.765411,0.968576,7.458341e-155,97.974630,0.777011,0.171163,0.303989)

In [10]:
data1=np.asarray(new_data)

In [13]:
reshape=data1.reshape(1,-1)

In [30]:
prediction = model.predict(reshape)
if prediction == 1:
  print("its an brain tumor")
else:
  print("its not an brain tumor")

its an brain tumor

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(