<a href="https://colab.research.google.com/github/Sumithra-08/cprogram/blob/main/Diabetics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [ ]:
df = pd.read_csv("/content/diabetes_2.csv")

In [ ]:
df.head(30)

    Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0             6      148             72  ...                     0.627   50        1
1             1       85             66  ...                     0.351   31        0
2             8      183             64  ...                     0.672   32        1
3             1       89             66  ...                     0.167   21        0
4             0      137             40  ...                     2.288   33        1
5             5      116             74  ...                     0.201   30        0
6             3       78             50  ...                     0.248   26        1
7            10      115              0  ...                     0.134   29        0
8             2      197             70  ...                     0.158   53        1
9             8      125             96  ...                     0.232   54        1
10            4      110             92  ...                     0.191   30        0
11           10      168             74  ...                     0.537   34        1
12           10      139             80  ...                     1.441   57        0
13            1      189             60  ...                     0.398   59        1
14            5      166             72  ...                     0.587   51        1
15            7      100              0  ...                     0.484   32        1
16            0      118             84  ...                     0.551   31        1
17            7      107             74  ...                     0.254   31        1
18            1      103             30  ...                     0.183   33        0
19            1      115             70  ...                     0.529   32        1
20            3      126             88  ...                     0.704   27        0
21            8       99             84  ...                     0.388   50        0
22            7      196             90  ...                     0.451   41        1
23            9      119             80  ...                     0.263   29        1
24           11      143             94  ...                     0.254   51        1
25           10      125             70  ...                     0.205   41        1
26            7      147             76  ...                     0.257   43        1
27            1       97             66  ...                     0.487   22        0
28           13      145             82  ...                     0.245   57        0
29            5      117             92  ...                     0.337   38        0

[30 rows x 9 columns]

In [ ]:
df.tail(5)

     Pregnancies  Glucose  ...  Age  Outcome
763           10      101  ...   63        0
764            2      122  ...   27        0
765            5      121  ...   30        0
766            1      126  ...   47        1
767            1       93  ...   23        0

[5 rows x 9 columns]

In [ ]:
X=df.drop(columns='Outcome',axis=1)
Y=df['Outcome']

In [ ]:
print(x)

     Pregnancies  Glucose  BloodPressure  ...   BMI  DiabetesPedigreeFunction  Age
0              6      148             72  ...  33.6                     0.627   50
1              1       85             66  ...  26.6                     0.351   31
2              8      183             64  ...  23.3                     0.672   32
3              1       89             66  ...  28.1                     0.167   21
4              0      137             40  ...  43.1                     2.288   33
..           ...      ...            ...  ...   ...                       ...  ...
763           10      101             76  ...  32.9                     0.171   63
764            2      122             70  ...  36.8                     0.340   27
765            5      121             72  ...  26.2                     0.245   30
766            1      126             60  ...  30.1                     0.349   47
767            1       93             70  ...  30.4                     0.315   23

[768 rows x 8 columns]

In [ ]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,stratify=Y,random_state=42)

In [ ]:
model=LogisticRegression()

In [ ]:
model.fit(X_train,Y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [ ]:
X_train_predict=model.predict(X_train)
Train_data_accuracy=accuracy_score(X_train_predict,Y_train)
print("Acccuracy score: ",Train_data_accuracy)

Acccuracy score:  0.7947882736156352

In [ ]:
X_test_predict=model.predict(X_test)
Test_data_accuracy=accuracy_score(X_test_predict,Y_test)
print("Acccuracy score: ",Test_data_accuracy)

Acccuracy score:  0.7142857142857143

In [ ]:
input=(1,85,66,29,0,26.6,0.351,31)

In [ ]:
numpy=np.asarray(input)

In [ ]:
numpy

array([ 1.   , 85.   , 66.   , 29.   ,  0.   , 26.6  ,  0.351, 31.   ])

In [ ]:
reshape=numpy.reshape(1,-1)

In [ ]:
reshape

array([[ 1.   , 85.   , 66.   , 29.   ,  0.   , 26.6  ,  0.351, 31.   ]])

In [ ]:
prediction= model.predict(reshape)
if prediction==1:
  print("Diabetic")
else:
  print("non Diabetic")

non Diabetic

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [ ]:
df.info(pd)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB